[package]
name = "sysy-rs"
version = "0.1.0"
authors = ["Peng Guanwen <pg999w@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
lalrpop-util = "0.19.5"
logos = "0.12.0"
pest = "2.1.3"
pest_derive = "2.1.0"
regex = "1.4.3"

[build-dependencies]
lalrpop = "0.19.5"
